[
    "Certificate of Currency",
    "XYZ Limited",
    "ABN 121 011100 54720   AFSL 81141141",
    "As at Date",
    "2 November 2015",
    "Policy Information",
    "Policy Type",
    "Professional",
    "Insured",
    "University of ABC and others as defined by the policy",
    "document.",
    "Insurer",
    "MMO Limited",
    "Policy Number(s)",
    "L0K107721013",
    "Period of Insurance",
    "From 4.00pm 1/11/2015 to 4.00pm 1/11/2016",
    "Interest Insured",
    "Loss incurred as a result of a civil liability claim made against the insured",
    "based solely on the insured’s provision of their professional services",
    "Limit of Liability",
    "$20,000,000 any one claim and $60,000,000 in the aggregate for all claims",
    "during the period of insurance. (Subject to the reinstatement provisions of",
    "the policy).",
    "ABN 121 011100 54720",
]
